//LOGIN AUTH
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

//CATEGORIES
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const REQUEST_CATEGORIES_FAILED = 'REQUEST_CATEGORIES_FAILED';
export const REQUEST_ADD_CATEGORIES = 'REQUEST_ADD_CATEGORIES';
export const ADD_CATEGORIES_SUCCESS = 'ADD_CATEGORIES_SUCCESS';
export const REQUEST_EDIT_CATEGORIES = 'REQUEST_EDIT_CATEGORIES';
export const EDIT_CATEGORIES_SUCCESS = 'EDIT_CATEGORIES_SUCCESS';
export const REQUEST_DELETE_CATEGORIES = 'DELETE_CATEGORIES';
export const DELETE_CATEGORIES_SUCCESS = 'DELETE_CATEGORIES_SUCCESS';
export const REQUEST_CHANGE_CATEGORIES_STATUS = 'REQUEST_CHANGE_CATEGORIES_STATUS';
export const CHANGE_CATEGORIES_STATUS_SUCCESS = 'CHANGE_CATEGORIES_STATUS_SUCCESS';

//LANGUAGES
export const REQUEST_LANGUAGES = 'REQUEST_LANGUAGES';
export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS';
export const REQUEST_LANGUAGES_FAILED = 'REQUEST_LANGUAGES_FAILED';
export const REQUEST_ADD_LANGUAGES = 'REQUEST_ADD_LANGUAGES';
export const ADD_LANGUAGES_SUCCESS = 'ADD_LANGUAGES_SUCCESS';
export const REQUEST_EDIT_LANGUAGES = 'REQUEST_EDIT_LANGUAGES';
export const EDIT_LANGUAGES_SUCCESS = 'EDIT_LANGUAGES_SUCCESS';
export const REQUEST_DELETE_LANGUAGES = 'REQUEST_DELETE_LANGUAGES';
export const DELETE_LANGUAGES_SUCCESS = 'DELETE_LANGUAGES_SUCCESS';

//NEWS
export const REQUEST_NEWS = 'REQUEST_NEWS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const REQUEST_NEWS_FAILED = 'REQUEST_NEWS_FAILED';
export const REQUEST_ADD_NEWS = 'REQUEST_ADD_NEWS';
export const ADD_NEWS_SUCCESS = 'ADD_NEWS_SUCCESS';
export const REQUEST_EDIT_NEWS = 'REQUEST_EDIT_NEWS';
export const EDIT_NEWS_SUCCESS = 'EDIT_NEWS_SUCCESS';
export const REQUEST_DELETE_NEWS= 'REQUEST_DELETE_NEWS';
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';

//PROVINCES
export const REQUEST_PROVINCES = 'REQUEST_PROVINCES';
export const GET_PROVINCES_SUCCESS = 'GET_PROVINCES_SUCCESS';
export const REQUEST_PROVINCES_FAILED = 'REQUEST_PROVINCES_FAILED';
export const REQUEST_ADD_PROVINCES = 'REQUEST_ADD_PROVINCES';
export const ADD_PROVINCES_SUCCESS = 'ADD_PROVINCES_SUCCESS';
export const REQUEST_EDIT_PROVINCES = 'REQUEST_EDIT_PROVINCES';
export const EDIT_PROVINCES_SUCCESS = 'EDIT_PROVINCES_SUCCESS';
export const REQUEST_DELETE_PROVINCES= 'REQUEST_DELETE_PROVINCES';
export const DELETE_PROVINCES_SUCCESS = 'DELETE_PROVINCES_SUCCESS';

//RESOURCES
export const REQUEST_RESOURCES = 'REQUEST_RESOURCES';
export const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
export const REQUEST_RESOURCES_FAILED = 'REQUEST_RESOURCES_FAILED';
export const REQUEST_ADD_RESOURCES = 'REQUEST_ADD_RESOURCES';
export const ADD_RESOURCES_SUCCESS = 'ADD_RESOURCES_SUCCESS';
export const REQUEST_EDIT_RESOURCES = 'REQUEST_EDIT_RESOURCES';
export const EDIT_RESOURCES_SUCCESS = 'EDIT_RESOURCES_SUCCESS';
export const REQUEST_DELETE_RESOURCES= 'REQUEST_DELETE_RESOURCES';
export const DELETE_RESOURCES_SUCCESS = 'DELETE_RESOURCES_SUCCESS';
