
//CATEGORIES
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const REQUEST_CATEGORIES_FAILED = 'REQUEST_CATEGORIES_FAILED';
export const REQUEST_ADD_CATEGORIES = 'REQUEST_ADD_CATEGORIES';
export const ADD_CATEGORIES_SUCCESS = 'ADD_CATEGORIES_SUCCESS';
export const REQUEST_EDIT_CATEGORIES = 'REQUEST_EDIT_CATEGORIES';
export const EDIT_CATEGORIES_SUCCESS = 'EDIT_CATEGORIES_SUCCESS';
export const REQUEST_DELETE_CATEGORIES = 'DELETE_CATEGORIES';
export const DELETE_CATEGORIES_SUCCESS = 'DELETE_CATEGORIES_SUCCESS';
export const REQUEST_ALL_CATEGORIES = 'REQUEST_ALL_CATEGORIES';
export const CATEGORIES_LIST_ALL = 'CATEGORIES_LIST_ALL';


//LANGUAGES
export const REQUEST_LANGUAGES = 'REQUEST_LANGUAGES';
export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS';
export const REQUEST_LANGUAGES_FAILED = 'REQUEST_LANGUAGES_FAILED';
export const REQUEST_ADD_LANGUAGES = 'REQUEST_ADD_LANGUAGES';
export const ADD_LANGUAGES_SUCCESS = 'ADD_LANGUAGES_SUCCESS';
export const REQUEST_EDIT_LANGUAGES = 'REQUEST_EDIT_LANGUAGES';
export const EDIT_LANGUAGES_SUCCESS = 'EDIT_LANGUAGES_SUCCESS';
export const REQUEST_DELETE_LANGUAGES = 'REQUEST_DELETE_LANGUAGES';
export const DELETE_LANGUAGES_SUCCESS = 'DELETE_LANGUAGES_SUCCESS';
export const ALL_LANGUAGE = 'ALL_LANGUAGE';
export const REQUEST_ALL_LANGUAGE = 'REQUEST_ALL_LANGUAGE';

//NEWS
export const REQUEST_NEWS = 'REQUEST_NEWS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const REQUEST_NEWS_FAILED = 'REQUEST_NEWS_FAILED';
export const REQUEST_ADD_NEWS = 'REQUEST_ADD_NEWS';
export const ADD_NEWS_SUCCESS = 'ADD_NEWS_SUCCESS';
export const REQUEST_EDIT_NEWS = 'REQUEST_EDIT_NEWS';
export const EDIT_NEWS_SUCCESS = 'EDIT_NEWS_SUCCESS';
export const REQUEST_DELETE_NEWS= 'REQUEST_DELETE_NEWS';
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';
export const ALL_NEWS = 'ALL_NEWS';
export const REQUEST_ALL_NEWS = 'REQUEST_ALL_NEWS';

//PROVINCES
export const REQUEST_PROVINCES = 'REQUEST_PROVINCES';
export const GET_PROVINCES_SUCCESS = 'GET_PROVINCES_SUCCESS';
export const REQUEST_PROVINCES_FAILED = 'REQUEST_PROVINCES_FAILED';
export const REQUEST_ADD_PROVINCES = 'REQUEST_ADD_PROVINCES';
export const ADD_PROVINCES_SUCCESS = 'ADD_PROVINCES_SUCCESS';
export const REQUEST_EDIT_PROVINCES = 'REQUEST_EDIT_PROVINCES';
export const EDIT_PROVINCES_SUCCESS = 'EDIT_PROVINCES_SUCCESS';
export const REQUEST_DELETE_PROVINCES= 'REQUEST_DELETE_PROVINCES';
export const DELETE_PROVINCES_SUCCESS = 'DELETE_PROVINCES_SUCCESS';
export const REQUEST_ALL_PROVINCE = 'REQUEST_ALL_PROVINCE'
export const ALL_PROVINCE = 'ALL_PROVINCE'

//RESOURCES
export const REQUEST_RESOURCES = 'REQUEST_RESOURCES';
export const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
export const REQUEST_RESOURCES_FAILED = 'REQUEST_RESOURCES_FAILED';
export const REQUEST_ADD_RESOURCES = 'REQUEST_ADD_RESOURCES';
export const ADD_RESOURCES_SUCCESS = 'ADD_RESOURCES_SUCCESS';
export const REQUEST_EDIT_RESOURCES = 'REQUEST_EDIT_RESOURCES';
export const EDIT_RESOURCES_SUCCESS = 'EDIT_RESOURCES_SUCCESS';
export const REQUEST_DELETE_RESOURCES= 'REQUEST_DELETE_RESOURCES';
export const DELETE_RESOURCES_SUCCESS = 'DELETE_RESOURCES_SUCCESS';
export const REQUEST_ALL_RESOURCES = 'REQUEST_ALL_RESOURCES';
export const ALL_RESOURCES = 'ALL_RESOURCES';

//CATEGORIES TRANSLATION
export const REQUEST_CATEGORIES_TRANSLATION = 'REQUEST_CATEGORIES_TRANSLATION';
export const GET_CATEGORIES_TRANSLATION_SUCCESS = 'GET_CATEGORIES_TRANSLATION_SUCCESS';
export const REQUEST_CATEGORIES_TRANSLATION_FAILED = 'REQUEST_CATEGORIES_TRANSLATION_FAILED';
export const REQUEST_ADD_CATEGORIES_TRANSLATION = 'REQUEST_ADD_CATEGORIES_TRANSLATION';
export const ADD_CATEGORIES_TRANSLATION_SUCCESS = 'ADD_CATEGORIES_TRANSLATION_SUCCESS';
export const REQUEST_EDIT_CATEGORIES_TRANSLATION = 'REQUEST_EDIT_CATEGORIES_TRANSLATION';
export const EDIT_CATEGORIES_TRANSLATION_SUCCESS = 'EDIT_CATEGORIES_TRANSLATION_SUCCESS';
export const REQUEST_DELETE_CATEGORIES_TRANSLATION= 'REQUEST_DELETE_CATEGORIES_TRANSLATION';
export const DELETE_CATEGORIES_TRANSLATION_SUCCESS = 'DELETE_CATEGORIES_TRANSLATION_SUCCESS';


//NEWS TRANSLATION
export const REQUEST_NEWS_TRANSLATION = 'REQUEST_NEWS_TRANSLATION';
export const GET_NEWS_TRANSLATION_SUCCESS = 'GET_NEWS_TRANSLATION_SUCCESS';
export const REQUEST_NEWS_TRANSLATION_FAILED = 'REQUEST_NEWS_TRANSLATION_FAILED';
export const REQUEST_ADD_NEWS_TRANSLATION = 'REQUEST_ADD_NEWS_TRANSLATION';
export const ADD_NEWS_TRANSLATION_SUCCESS = 'ADD_NEWS_TRANSLATION_SUCCESS';
export const REQUEST_EDIT_NEWS_TRANSLATION = 'REQUEST_EDIT_NEWS_TRANSLATION';
export const EDIT_NEWS_TRANSLATION_SUCCESS = 'EDIT_NEWS_TRANSLATION_SUCCESS';
export const REQUEST_DELETE_NEWS_TRANSLATION= 'REQUEST_DELETE_NEWS_TRANSLATION';
export const DELETE_NEWS_TRANSLATION_SUCCESS = 'DELETE_NEWS_TRANSLATION_SUCCESS';

//PROVINCE TRANSLATION
export const REQUEST_PROVINCE_TRANSLATION = 'REQUEST_PROVINCE_TRANSLATION';
export const GET_PROVINCE_TRANSLATION_SUCCESS = 'GET_PROVINCE_TRANSLATION_SUCCESS';
export const REQUEST_PROVINCE_TRANSLATION_FAILED = 'REQUEST_PROVINCE_TRANSLATION_FAILED';
export const REQUEST_ADD_PROVINCE_TRANSLATION = 'REQUEST_ADD_PROVINCE_TRANSLATION';
export const ADD_PROVINCE_TRANSLATION_SUCCESS = 'ADD_PROVINCE_TRANSLATION_SUCCESS';
export const REQUEST_EDIT_PROVINCE_TRANSLATION = 'REQUEST_EDIT_PROVINCE_TRANSLATION';
export const EDIT_PROVINCE_TRANSLATION_SUCCESS = 'EDIT_PROVINCE_TRANSLATION_SUCCESS';
export const REQUEST_DELETE_PROVINCE_TRANSLATION= 'REQUEST_DELETE_PROVINCE_TRANSLATION';
export const DELETE_PROVINCE_TRANSLATION_SUCCESS = 'DELETE_PROVINCE_TRANSLATION_SUCCESS';

//RESOURCE TRANSLATION
export const REQUEST_RESOURCE_TRANSLATION = 'REQUEST_RESOURCE_TRANSLATION';
export const GET_RESOURCE_TRANSLATION_SUCCESS = 'GET_RESOURCE_TRANSLATION_SUCCESS';
export const REQUEST_RESOURCE_TRANSLATION_FAILED = 'REQUEST_RESOURCE_TRANSLATION_FAILED';
export const REQUEST_ADD_RESOURCE_TRANSLATION = 'REQUEST_ADD_RESOURCE_TRANSLATION';
export const ADD_RESOURCE_TRANSLATION_SUCCESS = 'ADD_RESOURCE_TRANSLATION_SUCCESS';
export const REQUEST_EDIT_RESOURCE_TRANSLATION = 'REQUEST_EDIT_RESOURCE_TRANSLATION';
export const EDIT_RESOURCE_TRANSLATION_SUCCESS = 'EDIT_RESOURCE_TRANSLATION_SUCCESS';
export const REQUEST_DELETE_RESOURCE_TRANSLATION= 'REQUEST_DELETE_RESOURCE_TRANSLATION';
export const DELETE_RESOURCE_TRANSLATION_SUCCESS = 'DELETE_RESOURCE_TRANSLATION_SUCCESS';

//USERS ACTION TYPES
export const REQUEST_USERS = 'REQUEST_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED';
export const REQUEST_ADD_USERS = 'REQUEST_ADD_USERS';
export const ADD_USERS_SUCCESS = 'ADD_USERS_SUCCESS';
export const REQUEST_EDIT_USERS = 'REQUEST_EDIT_USERS';
export const EDIT_USERS_SUCCESS = 'EDIT_USERS_SUCCESS';
export const REQUEST_DELETE_USERS= 'REQUEST_DELETE_USERS';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';


//SUBSCRIBERS ACTION TYPES
export const REQUEST_SUBSCRIBERS = 'REQUEST_SUBSCRIBERS';
export const GET_SUBSCRIBERS_SUCCESS = 'GET_SUBSCRIBERS_SUCCESS';
export const REQUEST_SUBSCRIBERS_FAILED = 'REQUEST_SUBSCRIBERS_FAILED';
export const REQUEST_DELETE_SUBSCRIBERS= 'REQUEST_DELETE_SUBSCRIBERS';
export const DELETE_SUBSCRIBERS_SUCCESS = 'DELETE_SUBSCRIBERS_SUCCESS';
